name: PR Checks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.0

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm run check-types

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Check for build artifacts
        run: |
          echo "Checking build outputs..."
          ls -la apps/otter-server/dist/
          ls -la packages/*/dist/ || echo "No package dist directories found"

  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check formatting
        run: |
          pnpm run format
          if [ -n "$(git status --porcelain)" ]; then
            echo "Code is not formatted correctly. Please run 'pnpm run format' and commit the changes."
            git diff
            exit 1
          else
            echo "Code formatting is correct."
          fi
